### PR TITLE
Propose some functions and macros for unitful integration.

### PR DESCRIPTION
**Pull request by j-fu**
In particular this PR provides a `q_str` macro which accesses `u_str` to define quantities via the corresponding data in Unitful.

I don't know how to define the macros in the extension, so at this stage it would make Unitful a full dependency. IMHO would be ok, but of course this is open for discussion.

See my proposal in #10 - this PR could be an implementation.

### CODE REVIEW

**Comment by MilesCranmer** [comment]
Thanks for the PR! I am in principle on board with this, just need to consider things a bit more. I am wondering whether it makes sense to make Unitful.jl a hard dependency or not. According to the benchmark above, it bumps the load time to 0.6s. After #7, the load time would go down to 0.07s, so this would be a big increase if we do choose that route.

@oscardssmith thoughts?

I definitely like the idea of exporting a `q_str` though. I think you could export it from an extension by defining a macro that calls some function `_q_str`. Then overload that function inside the extension.

If we break the target audience into two groups, I see the following use-cases:

1. Internal use by package maintainers.
  - They might want to eliminate reliance on Unitful.jl completely, and just manipulate dimensions. Here, perhaps we just want to reduce load time of the package, and simplify things as much as possible.
  - I think this will be the main user base?
2. End users (people doing scientific calculations/analysis).
  - They probably want to use units.
  - They may want to try DynamicQuantities.jl for faster calculations.
  - Having them install both DynamicQuantities.jl and Unitful.jl (as well as importing both) would make things slightly less user-friendly.

In talking through this, I wonder if it makes the most sense to just have people import both packages, and convert between them. In other words, maybe it makes sense to keep Unitful.jl as an extension, without the `q_str` macro. Then they can still rely on the Unitful.jl documentation and other unit libraries, rather than treating DynamicQuantities.jl as a front-end API and expecting the relevant docs to be here. What do you think?

**Comment by MilesCranmer** [comment]
@odow I'd be interested to hear your thoughts as well

**Comment by j-fu** [comment]
Interesting considerations! 

My opinion here is that Unitful.jl is too rigid to be used by end users (who ase a rule are inexperienced programers and don't see programming as their foremost purpose). `km` and `cm` being different types feels IMHO is not very intuitive. I am working  with others on a PDE simulation stack for applicationsm and I really would like to provide the possibility to do calculations with units to end users and modelers. With Unitful one needs to strip units before going into the solver (and not forget upreferred - I once [tried](https://github.com/PainterQubits/Unitful.jl/pull/448) to get some convenience calls which should have made it easier for end users into Unitful). 
For me this ended up in [LessUnitful.jl](https://j-fu.github.io/LessUnitful.jl/stable/) which is just a band aid.

For `DyanamicQuantities` I indeed see the potential that this package can work well for less experienced end users. I see the potential that quanties can be passed through e.g. a PDE solver if it is well designed. This opens up great possibilities for simulation work, teaching etc.

I see the need for being able to expose end users to quantities with units  in an easy to handle consistent way, Julia and its ecosystem certainly have the potential, and DynamicQuanties could make it possible.  So indeed I would put them first...

**Comment by j-fu** [comment]
Ok the wind blew the other direction, so I think we can close this.

**Pull request closed without merging**
